name: 'Notion To Static File'
description: 'Reads from a Notion Database and auto generates a JSON/YML file'
inputs:
  notion-token:
    description: 'Notion token'
    required: true
  notion-db:
    description: 'Notion database'
    required: true
  output-file:
    description: 'File to output'
    required: true
  output-format:
    description: 'File format to output. Normally deduced from file output extension.'
    required: false
  ignore-columns:
    description: 'If any, ignore the columns specified by name'
    required: false
  body-format:
    description: 'If any, include the notion page body with none, markdown or html options'
    default: 'none'
    required: false
  keys-camelcase:
    description: 'Keys camelCase'
    required: false
    default: 'false'
  keys-dot-expansion:
    description: 'Keys dot expansion'
    required: false
    default: 'false'
outputs:
  updated:
    description: 'Whether it was updated or not'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: "refresh-cw"
  color: "green"
